name: flutter_utility
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  shelf: ^1.4.0
  shelf_static: ^1.1.0
  shelf_multipart: ^2.0.1
  mime: ^1.0.4
  http_parser: ^4.0.0
  network_info_plus: ^6.1.4
  permission_handler: ^12.0.1
  flutter_background: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

